<?php

namespace Database\Seeders;

use App\Models\Accommodation;
use App\Models\TouristCategory;
use App\Models\TouristCity;
use Illuminate\Database\Seeder;

class AccommodationSeeder extends Seeder
{
    public function run(): void
    {
        // Résoudre les IDs par slug une seule fois
        $c = TouristCity::pluck('id', 'slug');
        $k = TouristCategory::pluck('id', 'slug');

        $accommodations = [

            // ══════════════════════════════════════════════════════
            // ABIDJAN
            // ══════════════════════════════════════════════════════

            [
                'city_id'           => $c['abidjan'],
                'name'              => 'Sofitel Abidjan Hôtel Ivoire',
                'slug'              => 'sofitel-abidjan-hotel-ivoire',
                'type'              => 'hotel',
                'stars'             => 5,
                'short_description' => 'Icône d\'Abidjan depuis 1963, ce palace 5 étoiles domine le Plateau avec vue sur la lagune Ébrié.',
                'description'       => "Inauguré en 1963 et entièrement rénové, le Sofitel Abidjan Hôtel Ivoire est le symbole de l'élégance ivoirienne. Niché sur les hauteurs de Cocody, il offre une vue panoramique sur la lagune Ébrié et le skyline d'Abidjan. Le complexe dispose d'une patinoire, d'un bowling, d'un casino, de plusieurs restaurants gastronomiques et d'un spa de renommée internationale.",
                'adresse'           => 'Boulevard Hassan II, Cocody',
                'quartier'          => 'Cocody',
                'latitude'          => 5.3600,
                'longitude'         => -4.0080,
                'phone'             => '+225 27 22 48 26 00',
                'email'             => 'h1394@sofitel.com',
                'website'           => 'https://sofitel.accor.com',
                'check_in_time'     => '15:00',
                'check_out_time'    => '12:00',
                'amenities'         => [
                    ['icon' => 'fas fa-wifi',           'label' => 'Wi-Fi gratuit'],
                    ['icon' => 'fas fa-swimming-pool',  'label' => 'Piscine olympique'],
                    ['icon' => 'fas fa-spa',            'label' => 'Spa & bien-être'],
                    ['icon' => 'fas fa-utensils',       'label' => '4 restaurants'],
                    ['icon' => 'fas fa-dumbbell',       'label' => 'Salle de sport'],
                    ['icon' => 'fas fa-car',            'label' => 'Parking valet'],
                    ['icon' => 'fas fa-dice',           'label' => 'Casino'],
                    ['icon' => 'fas fa-concierge-bell', 'label' => 'Concierge 24h/24'],
                ],
                'category_ids'      => [
                    $k['monuments-patrimoine'],
                    $k['vie-nocturne-divertissement'],
                    $k['gastronomie-maquis'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Chambre Supérieure',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 32,
                        'price_xof'    => 120000,
                        'price_eur'    => 183,
                        'amenities'    => ['Climatisation', 'Coffre-fort', 'Minibar', 'TV écran plat'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Chambre Deluxe Vue Lagune',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 38,
                        'price_xof'    => 165000,
                        'price_eur'    => 252,
                        'amenities'    => ['Vue lagune', 'Balcon', 'Baignoire', 'Peignoirs'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Suite Junior',
                        'max_adults'   => 2,
                        'max_children' => 2,
                        'area_m2'      => 60,
                        'price_xof'    => 280000,
                        'price_eur'    => 427,
                        'amenities'    => ['Salon séparé', 'Jacuzzi', 'Service de chambre 24h/24'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Booking.com',  'logo_url' => null, 'affiliate_url' => 'https://www.booking.com/hotel/ci/sofitel-abidjan-hotel-ivoire.fr.html', 'is_official' => false, 'badge_text' => null,            'sort_order' => 1],
                    ['provider_name' => 'Accor',        'logo_url' => null, 'affiliate_url' => 'https://sofitel.accor.com',                                              'is_official' => true,  'badge_text' => 'Site officiel',  'sort_order' => 0],
                    ['provider_name' => 'Expedia',      'logo_url' => null, 'affiliate_url' => 'https://www.expedia.fr',                                                 'is_official' => false, 'badge_text' => null,            'sort_order' => 2],
                ],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 1,
            ],

            [
                'city_id'           => $c['abidjan'],
                'name'              => 'Pullman Abidjan',
                'slug'              => 'pullman-abidjan',
                'type'              => 'hotel',
                'stars'             => 5,
                'short_description' => 'Hôtel d\'affaires 5 étoiles au cœur du Plateau, à deux pas du Port Autonome d\'Abidjan.',
                'description'       => "Le Pullman Abidjan est l'adresse de référence pour les voyageurs d'affaires en Côte d'Ivoire. Situé au cœur du quartier des affaires du Plateau, il propose des espaces de réunion ultramodernes, un rooftop avec vue imprenable sur la lagune et les meilleurs standards de la chaîne Accor.",
                'adresse'           => 'Rue Gourgas, Le Plateau',
                'quartier'          => 'Le Plateau',
                'latitude'          => 5.3231,
                'longitude'         => -4.0220,
                'phone'             => '+225 27 20 30 30 00',
                'email'             => 'info@pullman-abidjan.com',
                'website'           => 'https://pullman.accor.com',
                'check_in_time'     => '14:00',
                'check_out_time'    => '12:00',
                'amenities'         => [
                    ['icon' => 'fas fa-wifi',           'label' => 'Wi-Fi haut débit'],
                    ['icon' => 'fas fa-swimming-pool',  'label' => 'Piscine rooftop'],
                    ['icon' => 'fas fa-briefcase',      'label' => 'Centre d\'affaires'],
                    ['icon' => 'fas fa-utensils',       'label' => 'Restaurant panoramique'],
                    ['icon' => 'fas fa-car',            'label' => 'Navette aéroport'],
                    ['icon' => 'fas fa-dumbbell',       'label' => 'Fitness center'],
                ],
                'category_ids'      => [
                    $k['monuments-patrimoine'],
                    $k['vie-nocturne-divertissement'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Chambre Supérieure',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 30,
                        'price_xof'    => 110000,
                        'price_eur'    => 168,
                        'amenities'    => ['Climatisation', 'Minibar', 'Coffre-fort', 'Bureau de travail'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Chambre Deluxe',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 36,
                        'price_xof'    => 145000,
                        'price_eur'    => 221,
                        'amenities'    => ['Vue ville', 'Baignoire', 'Nespresso', 'TV 55"'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Booking.com', 'logo_url' => null, 'affiliate_url' => 'https://www.booking.com/hotel/ci/pullman-abidjan.fr.html', 'is_official' => false, 'badge_text' => 'Meilleur prix', 'sort_order' => 1],
                    ['provider_name' => 'Accor',       'logo_url' => null, 'affiliate_url' => 'https://pullman.accor.com',                                'is_official' => true,  'badge_text' => 'Site officiel',  'sort_order' => 0],
                    ['provider_name' => 'Agoda',       'logo_url' => null, 'affiliate_url' => 'https://www.agoda.com',                                    'is_official' => false, 'badge_text' => null,             'sort_order' => 2],
                ],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 2,
            ],

            [
                'city_id'           => $c['abidjan'],
                'name'              => 'Hôtel du Golf',
                'slug'              => 'hotel-du-golf-abidjan',
                'type'              => 'hotel',
                'stars'             => 4,
                'short_description' => 'Hôtel 4 étoiles niché dans un écrin de verdure à Cocody, face au Golf Club d\'Abidjan.',
                'description'       => "L'Hôtel du Golf bénéficie d'un cadre exceptionnel en plein cœur du quartier résidentiel de Cocody. Ses chambres donnent sur un parcours de golf de 18 trous, offrant une atmosphère calme et reposante loin de l'agitation de la ville.",
                'adresse'           => 'Boulevard de France, Cocody',
                'quartier'          => 'Cocody',
                'latitude'          => 5.3680,
                'longitude'         => -3.9920,
                'phone'             => '+225 27 22 44 10 00',
                'email'             => null,
                'website'           => null,
                'check_in_time'     => '14:00',
                'check_out_time'    => '11:00',
                'amenities'         => [
                    ['icon' => 'fas fa-golf-ball',     'label' => 'Accès golf 18 trous'],
                    ['icon' => 'fas fa-swimming-pool', 'label' => 'Piscine extérieure'],
                    ['icon' => 'fas fa-wifi',          'label' => 'Wi-Fi gratuit'],
                    ['icon' => 'fas fa-utensils',      'label' => 'Restaurant & bar'],
                    ['icon' => 'fas fa-car',           'label' => 'Parking gratuit'],
                ],
                'category_ids'      => [
                    $k['sports-aventure'],
                    $k['parcs-espaces-naturels'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Chambre Standard',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 26,
                        'price_xof'    => 65000,
                        'price_eur'    => 99,
                        'amenities'    => ['Climatisation', 'TV satellite', 'Wifi'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Chambre Vue Golf',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 30,
                        'price_xof'    => 85000,
                        'price_eur'    => 130,
                        'amenities'    => ['Vue golf', 'Terrasse', 'Minibar'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Booking.com', 'logo_url' => null, 'affiliate_url' => 'https://www.booking.com', 'is_official' => false, 'badge_text' => null, 'sort_order' => 1],
                    ['provider_name' => 'Expedia',     'logo_url' => null, 'affiliate_url' => 'https://www.expedia.fr',  'is_official' => false, 'badge_text' => null, 'sort_order' => 2],
                ],
                'is_featured'       => false,
                'is_active'         => true,
                'sort_order'        => 3,
            ],

            // ══════════════════════════════════════════════════════
            // YAMOUSSOUKRO
            // ══════════════════════════════════════════════════════

            [
                'city_id'           => $c['yamoussoukro'],
                'name'              => 'Hôtel Président Yamoussoukro',
                'slug'              => 'hotel-president-yamoussoukro',
                'type'              => 'hotel',
                'stars'             => 4,
                'short_description' => 'L\'hôtel officiel de la capitale politique, à quelques minutes de la Basilique Notre-Dame de la Paix.',
                'description'       => "Ancienne résidence officielle de Félix Houphouët-Boigny, l'Hôtel Président est une institution de Yamoussoukro. Ses jardins tropicaux, son lac aux crocodiles sacrés et sa proximité avec la Basilique Notre-Dame de la Paix en font une étape incontournable.",
                'adresse'           => 'Avenue Houphouët-Boigny, Yamoussoukro',
                'quartier'          => 'Centre',
                'latitude'          => 6.8280,
                'longitude'         => -5.2893,
                'phone'             => '+225 30 64 90 00',
                'email'             => 'reservation@hotelpresident-yamoussoukro.com',
                'website'           => 'https://www.hotelpresident-yamoussoukro.com',
                'check_in_time'     => '14:00',
                'check_out_time'    => '12:00',
                'amenities'         => [
                    ['icon' => 'fas fa-swimming-pool',  'label' => 'Piscine'],
                    ['icon' => 'fas fa-wifi',           'label' => 'Wi-Fi gratuit'],
                    ['icon' => 'fas fa-utensils',       'label' => 'Restaurant gastronomique'],
                    ['icon' => 'fas fa-frog',           'label' => 'Lac aux crocodiles'],
                    ['icon' => 'fas fa-car',            'label' => 'Parking sécurisé'],
                    ['icon' => 'fas fa-tree',           'label' => 'Jardins tropicaux'],
                ],
                'category_ids'      => [
                    $k['architecture-sacree'],
                    $k['monuments-patrimoine'],
                    $k['sites-historiques'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Chambre Standard',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 28,
                        'price_xof'    => 55000,
                        'price_eur'    => 84,
                        'amenities'    => ['Climatisation', 'TV satellite', 'Wifi', 'Vue jardin'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Chambre Supérieure',
                        'max_adults'   => 2,
                        'max_children' => 2,
                        'area_m2'      => 34,
                        'price_xof'    => 75000,
                        'price_eur'    => 114,
                        'amenities'    => ['Vue piscine', 'Baignoire', 'Minibar'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Suite Présidentielle',
                        'max_adults'   => 2,
                        'max_children' => 0,
                        'area_m2'      => 90,
                        'price_xof'    => 200000,
                        'price_eur'    => 305,
                        'amenities'    => ['Salon privé', 'Jacuzzi', 'Butler', 'Vue panoramique'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Site officiel', 'logo_url' => null, 'affiliate_url' => 'https://www.hotelpresident-yamoussoukro.com', 'is_official' => true,  'badge_text' => 'Meilleur tarif garanti', 'sort_order' => 0],
                    ['provider_name' => 'Booking.com',   'logo_url' => null, 'affiliate_url' => 'https://www.booking.com',                    'is_official' => false, 'badge_text' => null,                    'sort_order' => 1],
                ],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 1,
            ],

            [
                'city_id'           => $c['yamoussoukro'],
                'name'              => 'Silva Hôtel Yamoussoukro',
                'slug'              => 'silva-hotel-yamoussoukro',
                'type'              => 'hotel',
                'stars'             => 3,
                'short_description' => 'Hôtel 3 étoiles confortable, idéal pour les pèlerins et touristes visitant la Basilique.',
                'description'       => "Le Silva Hôtel est une option abordable et bien située pour découvrir Yamoussoukro. À 10 minutes à pied de la Basilique Notre-Dame de la Paix, il accueille aussi bien les pèlerins que les touristes avec un service chaleureux.",
                'adresse'           => 'Rue des Baobabs, Yamoussoukro',
                'quartier'          => 'Centre',
                'latitude'          => 6.8210,
                'longitude'         => -5.2820,
                'phone'             => '+225 30 64 22 00',
                'email'             => null,
                'website'           => null,
                'check_in_time'     => '13:00',
                'check_out_time'    => '11:00',
                'amenities'         => [
                    ['icon' => 'fas fa-wifi',          'label' => 'Wi-Fi gratuit'],
                    ['icon' => 'fas fa-utensils',      'label' => 'Restaurant'],
                    ['icon' => 'fas fa-car',           'label' => 'Parking gratuit'],
                    ['icon' => 'fas fa-snowflake',     'label' => 'Climatisation'],
                ],
                'category_ids'      => [
                    $k['architecture-sacree'],
                    $k['sites-historiques'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Chambre Simple',
                        'max_adults'   => 1,
                        'max_children' => 0,
                        'area_m2'      => 18,
                        'price_xof'    => 25000,
                        'price_eur'    => 38,
                        'amenities'    => ['Climatisation', 'Salle de bain privée', 'Wifi'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Chambre Double',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 24,
                        'price_xof'    => 38000,
                        'price_eur'    => 58,
                        'amenities'    => ['Grand lit', 'TV', 'Climatisation'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Booking.com', 'logo_url' => null, 'affiliate_url' => 'https://www.booking.com', 'is_official' => false, 'badge_text' => null, 'sort_order' => 1],
                ],
                'is_featured'       => false,
                'is_active'         => true,
                'sort_order'        => 2,
            ],

            // ══════════════════════════════════════════════════════
            // GRAND-BASSAM
            // ══════════════════════════════════════════════════════

            [
                'city_id'           => $c['grand-bassam'],
                'name'              => 'La Maison Coloniale',
                'slug'              => 'maison-coloniale-grand-bassam',
                'type'              => 'guesthouse',
                'stars'             => 3,
                'short_description' => 'Maison d\'hôtes de charme dans une villa coloniale classée, en plein cœur du quartier historique de Grand-Bassam.',
                'description'       => "Installée dans une authentique villa coloniale du XIXe siècle, La Maison Coloniale offre une immersion unique dans l'architecture et l'atmosphère de Grand-Bassam, première capitale de la Côte d'Ivoire. Ses hauts plafonds, ses grandes vérandas et son jardin ombragé en font un lieu hors du temps.",
                'adresse'           => 'Quartier France, Grand-Bassam',
                'quartier'          => 'Quartier France',
                'latitude'          => 5.2000,
                'longitude'         => -3.7450,
                'phone'             => '+225 07 07 07 07 07',
                'email'             => 'contact@maisoncoloniale-bassam.ci',
                'website'           => null,
                'check_in_time'     => '14:00',
                'check_out_time'    => '11:00',
                'amenities'         => [
                    ['icon' => 'fas fa-wifi',          'label' => 'Wi-Fi gratuit'],
                    ['icon' => 'fas fa-umbrella-beach','label' => 'Accès plage privée'],
                    ['icon' => 'fas fa-utensils',      'label' => 'Petit-déjeuner inclus'],
                    ['icon' => 'fas fa-fan',           'label' => 'Ventilateurs & clim'],
                    ['icon' => 'fas fa-tree',          'label' => 'Jardin colonial'],
                    ['icon' => 'fas fa-bicycle',       'label' => 'Location de vélos'],
                ],
                'category_ids'      => [
                    $k['sites-historiques'],
                    $k['monuments-patrimoine'],
                    $k['plages-lagunes'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Chambre Coloniale',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 22,
                        'price_xof'    => 45000,
                        'price_eur'    => 69,
                        'amenities'    => ['Lit en fer forgé', 'Moustiquaire', 'Ventilateur', 'Salle de bain ancienne'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Suite Véranda',
                        'max_adults'   => 2,
                        'max_children' => 0,
                        'area_m2'      => 35,
                        'price_xof'    => 65000,
                        'price_eur'    => 99,
                        'amenities'    => ['Grande véranda privée', 'Baignoire sur pieds', 'Vue jardin'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Booking.com', 'logo_url' => null, 'affiliate_url' => 'https://www.booking.com', 'is_official' => false, 'badge_text' => 'Remboursable',  'sort_order' => 1],
                    ['provider_name' => 'Airbnb',      'logo_url' => null, 'affiliate_url' => 'https://www.airbnb.fr',   'is_official' => false, 'badge_text' => null,            'sort_order' => 2],
                ],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 1,
            ],

            [
                'city_id'           => $c['grand-bassam'],
                'name'              => 'Hôtel de la Plage Bassam',
                'slug'              => 'hotel-plage-bassam',
                'type'              => 'hotel',
                'stars'             => 3,
                'short_description' => 'Hôtel de bord de mer avec accès direct à la plage de Grand-Bassam, idéal pour les week-ends.',
                'description'       => "L'Hôtel de la Plage est le choix préféré des Abidjanais pour leurs escapades de week-end. Situé directement sur la plage de Grand-Bassam, il propose des chambres avec vue mer et une terrasse balnéaire animée.",
                'adresse'           => 'Bord de mer, Grand-Bassam',
                'quartier'          => 'Bord de mer',
                'latitude'          => 5.1950,
                'longitude'         => -3.7400,
                'phone'             => '+225 27 21 30 10 00',
                'email'             => null,
                'website'           => null,
                'check_in_time'     => '13:00',
                'check_out_time'    => '11:00',
                'amenities'         => [
                    ['icon' => 'fas fa-umbrella-beach', 'label' => 'Plage privée'],
                    ['icon' => 'fas fa-swimming-pool',  'label' => 'Piscine'],
                    ['icon' => 'fas fa-wifi',           'label' => 'Wi-Fi'],
                    ['icon' => 'fas fa-utensils',       'label' => 'Restaurant fruits de mer'],
                    ['icon' => 'fas fa-car',            'label' => 'Parking'],
                ],
                'category_ids'      => [
                    $k['plages-lagunes'],
                    $k['sites-historiques'],
                    $k['gastronomie-maquis'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Chambre Vue Mer',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 24,
                        'price_xof'    => 50000,
                        'price_eur'    => 76,
                        'amenities'    => ['Vue mer', 'Balcon', 'Climatisation'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Bungalow Plage',
                        'max_adults'   => 2,
                        'max_children' => 2,
                        'area_m2'      => 40,
                        'price_xof'    => 80000,
                        'price_eur'    => 122,
                        'amenities'    => ['Accès direct plage', 'Terrasse privée', 'Hammac'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Booking.com', 'logo_url' => null, 'affiliate_url' => 'https://www.booking.com', 'is_official' => false, 'badge_text' => null, 'sort_order' => 1],
                ],
                'is_featured'       => false,
                'is_active'         => true,
                'sort_order'        => 2,
            ],

            // ══════════════════════════════════════════════════════
            // ASSINIE
            // ══════════════════════════════════════════════════════

            [
                'city_id'           => $c['assinie'],
                'name'              => 'Assinie Beach Resort',
                'slug'              => 'assinie-beach-resort',
                'type'              => 'resort',
                'stars'             => 4,
                'short_description' => 'Resort de luxe sur la péninsule d\'Assinie, entre océan Atlantique et lagune Aby.',
                'description'       => "L'Assinie Beach Resort occupe une position unique sur l'étroite péninsule d'Assinie, avec d'un côté les vagues de l'Atlantique et de l'autre la tranquillité de la lagune Aby. Ce resort 4 étoiles est le paradis des amateurs de water sports, de pêche et de détente absolue.",
                'adresse'           => 'Péninsule d\'Assinie',
                'quartier'          => 'Assinie-Mafia',
                'latitude'          => 5.1430,
                'longitude'         => -3.4640,
                'phone'             => '+225 07 08 09 10 11',
                'email'             => 'resa@assinie-resort.ci',
                'website'           => 'https://www.assinie-resort.ci',
                'check_in_time'     => '15:00',
                'check_out_time'    => '11:00',
                'amenities'         => [
                    ['icon' => 'fas fa-umbrella-beach', 'label' => 'Plage océan & lagune'],
                    ['icon' => 'fas fa-swimming-pool',  'label' => 'Piscine à débordement'],
                    ['icon' => 'fas fa-water',          'label' => 'Sports nautiques'],
                    ['icon' => 'fas fa-fish',           'label' => 'Pêche sportive'],
                    ['icon' => 'fas fa-spa',            'label' => 'Spa & massages'],
                    ['icon' => 'fas fa-utensils',       'label' => 'Restaurant & beach bar'],
                    ['icon' => 'fas fa-wifi',           'label' => 'Wi-Fi'],
                    ['icon' => 'fas fa-ship',           'label' => 'Transfert en pirogue'],
                ],
                'category_ids'      => [
                    $k['plages-lagunes'],
                    $k['sports-aventure'],
                    $k['lacs-cours-eau'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Bungalow Lagune',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 36,
                        'price_xof'    => 95000,
                        'price_eur'    => 145,
                        'amenities'    => ['Vue lagune', 'Terrasse privée', 'Hamac', 'Clim'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Suite Océan',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 50,
                        'price_xof'    => 145000,
                        'price_eur'    => 221,
                        'amenities'    => ['Vue océan', 'Accès direct plage', 'Jacuzzi extérieur'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Villa Familiale',
                        'max_adults'   => 4,
                        'max_children' => 3,
                        'area_m2'      => 90,
                        'price_xof'    => 250000,
                        'price_eur'    => 381,
                        'amenities'    => ['2 chambres', 'Cuisine équipée', 'Piscine privée', 'Barbecue'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Site officiel', 'logo_url' => null, 'affiliate_url' => 'https://www.assinie-resort.ci',  'is_official' => true,  'badge_text' => 'Meilleur prix garanti', 'sort_order' => 0],
                    ['provider_name' => 'Booking.com',   'logo_url' => null, 'affiliate_url' => 'https://www.booking.com',        'is_official' => false, 'badge_text' => 'Remboursable',         'sort_order' => 1],
                    ['provider_name' => 'Expedia',       'logo_url' => null, 'affiliate_url' => 'https://www.expedia.fr',         'is_official' => false, 'badge_text' => null,                   'sort_order' => 2],
                ],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 1,
            ],

            // ══════════════════════════════════════════════════════
            // MAN
            // ══════════════════════════════════════════════════════

            [
                'city_id'           => $c['man'],
                'name'              => 'Hôtel Les Cascades de Man',
                'slug'              => 'hotel-cascades-man',
                'type'              => 'hotel',
                'stars'             => 3,
                'short_description' => 'Hôtel de montagne au pied des cascades de Man, porte d\'entrée du pays Dan.',
                'description'       => "Idéalement situé à Man, ville des Dan et des hommes-panthères, l'Hôtel Les Cascades est le point de départ idéal pour explorer les cascades de la Zouzoukrou, le mont Nimba et les villages traditionnels. Son cadre montagneux en fait l'une des adresses les plus pittoresques du pays.",
                'adresse'           => 'Route des Cascades, Man',
                'quartier'          => 'Centre',
                'latitude'          => 7.4130,
                'longitude'         => -7.5540,
                'phone'             => '+225 33 79 01 23',
                'email'             => null,
                'website'           => null,
                'check_in_time'     => '13:00',
                'check_out_time'    => '11:00',
                'amenities'         => [
                    ['icon' => 'fas fa-mountain',      'label' => 'Vue montagne'],
                    ['icon' => 'fas fa-wifi',          'label' => 'Wi-Fi'],
                    ['icon' => 'fas fa-utensils',      'label' => 'Restaurant'],
                    ['icon' => 'fas fa-hiking',        'label' => 'Guides randonnée'],
                    ['icon' => 'fas fa-car',           'label' => 'Parking'],
                ],
                'category_ids'      => [
                    $k['cascades-montagnes'],
                    $k['parcs-reserves-naturelles'],
                    $k['villages-ethnies'],
                    $k['sites-culturels'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Chambre Standard',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 20,
                        'price_xof'    => 28000,
                        'price_eur'    => 43,
                        'amenities'    => ['Climatisation', 'Salle de bain privée', 'Wifi'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Chambre Vue Cascade',
                        'max_adults'   => 2,
                        'max_children' => 0,
                        'area_m2'      => 25,
                        'price_xof'    => 42000,
                        'price_eur'    => 64,
                        'amenities'    => ['Vue sur cascade', 'Balcon', 'Petit-déjeuner inclus'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Booking.com', 'logo_url' => null, 'affiliate_url' => 'https://www.booking.com', 'is_official' => false, 'badge_text' => null, 'sort_order' => 1],
                ],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 1,
            ],

            [
                'city_id'           => $c['man'],
                'name'              => 'Éco-Lodge Nimba',
                'slug'              => 'eco-lodge-nimba-man',
                'type'              => 'eco_lodge',
                'stars'             => 2,
                'short_description' => 'Éco-lodge immergé dans la forêt tropicale aux abords du mont Nimba, réserve de biosphère UNESCO.',
                'description'       => "L'Éco-Lodge Nimba propose une expérience d'hébergement respectueuse de l'environnement au cœur de la forêt dense de l'Ouest ivoirien. Les cases en matériaux locaux permettent une immersion totale dans la nature, à deux pas du mont Nimba classé au patrimoine mondial de l'UNESCO.",
                'adresse'           => 'Forêt de Biankouma',
                'quartier'          => 'Périphérie',
                'latitude'          => 7.6200,
                'longitude'         => -7.7300,
                'phone'             => '+225 07 12 34 56 78',
                'email'             => 'nimba.ecolodge@gmail.com',
                'website'           => null,
                'check_in_time'     => '14:00',
                'check_out_time'    => '10:00',
                'amenities'         => [
                    ['icon' => 'fas fa-leaf',     'label' => 'Éco-responsable'],
                    ['icon' => 'fas fa-fire',     'label' => 'Feux de camp'],
                    ['icon' => 'fas fa-binoculars','label' => 'Safari faune'],
                    ['icon' => 'fas fa-hiking',   'label' => 'Randonnées guidées'],
                    ['icon' => 'fas fa-utensils', 'label' => 'Cuisine locale'],
                ],
                'category_ids'      => [
                    $k['parcs-reserves-naturelles'],
                    $k['cascades-montagnes'],
                    $k['sports-aventure'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Case Traditionnelle',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 16,
                        'price_xof'    => 18000,
                        'price_eur'    => 27,
                        'amenities'    => ['Moustiquaire', 'Ventilateur', 'Douche froide'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Airbnb', 'logo_url' => null, 'affiliate_url' => 'https://www.airbnb.fr', 'is_official' => false, 'badge_text' => null, 'sort_order' => 1],
                ],
                'is_featured'       => false,
                'is_active'         => true,
                'sort_order'        => 2,
            ],

            // ══════════════════════════════════════════════════════
            // KORHOGO
            // ══════════════════════════════════════════════════════

            [
                'city_id'           => $c['korhogo'],
                'name'              => 'Mont Korhogo Hôtel',
                'slug'              => 'mont-korhogo-hotel',
                'type'              => 'hotel',
                'stars'             => 3,
                'short_description' => 'Hôtel central à Korhogo, capitale des Sénoufo et du textile ivoirien.',
                'description'       => "Situé au cœur de Korhogo, capitale de la région des Savanes et ville emblématique des Sénoufo, le Mont Korhogo Hôtel est la base idéale pour découvrir les villages de tisserands, les masques Poro et la savane du nord ivoirien.",
                'adresse'           => 'Avenue de la Liberté, Korhogo',
                'quartier'          => 'Centre-ville',
                'latitude'          => 9.4580,
                'longitude'         => -5.6290,
                'phone'             => '+225 36 86 02 00',
                'email'             => null,
                'website'           => null,
                'check_in_time'     => '13:00',
                'check_out_time'    => '11:00',
                'amenities'         => [
                    ['icon' => 'fas fa-swimming-pool', 'label' => 'Piscine'],
                    ['icon' => 'fas fa-wifi',          'label' => 'Wi-Fi'],
                    ['icon' => 'fas fa-utensils',      'label' => 'Restaurant'],
                    ['icon' => 'fas fa-car',           'label' => 'Parking'],
                    ['icon' => 'fas fa-route',         'label' => 'Excursions organisées'],
                ],
                'category_ids'      => [
                    $k['villages-ethnies'],
                    $k['sites-culturels'],
                    $k['artisanat-marches'],
                    $k['ceremonies-rituels'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Chambre Standard',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 22,
                        'price_xof'    => 30000,
                        'price_eur'    => 46,
                        'amenities'    => ['Climatisation', 'TV', 'Salle de bain privée'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Suite Sénoufo',
                        'max_adults'   => 2,
                        'max_children' => 0,
                        'area_m2'      => 40,
                        'price_xof'    => 55000,
                        'price_eur'    => 84,
                        'amenities'    => ['Décoration artisanale', 'Minibar', 'Baignoire'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Booking.com', 'logo_url' => null, 'affiliate_url' => 'https://www.booking.com', 'is_official' => false, 'badge_text' => null, 'sort_order' => 1],
                ],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 1,
            ],

            // ══════════════════════════════════════════════════════
            // SAN-PÉDRO
            // ══════════════════════════════════════════════════════

            [
                'city_id'           => $c['san-pedro'],
                'name'              => 'Hôtel Balmer San-Pédro',
                'slug'              => 'hotel-balmer-san-pedro',
                'type'              => 'hotel',
                'stars'             => 4,
                'short_description' => 'Le meilleur hôtel de San-Pédro, face à l\'océan, porte d\'entrée du parc national de Taï.',
                'description'       => "L'Hôtel Balmer est la référence à San-Pédro. Sa piscine surplombant l'océan Atlantique, ses chambres avec vue mer et sa proximité avec le deuxième port du pays en font une adresse de choix pour les voyageurs d'affaires et les touristes en route vers le parc de Taï.",
                'adresse'           => 'Bord de mer, San-Pédro',
                'quartier'          => 'Bord de mer',
                'latitude'          => 4.7480,
                'longitude'         => -6.6360,
                'phone'             => '+225 34 71 22 33',
                'email'             => 'info@hotelbalmer.ci',
                'website'           => null,
                'check_in_time'     => '14:00',
                'check_out_time'    => '12:00',
                'amenities'         => [
                    ['icon' => 'fas fa-swimming-pool',  'label' => 'Piscine vue mer'],
                    ['icon' => 'fas fa-umbrella-beach', 'label' => 'Accès plage'],
                    ['icon' => 'fas fa-wifi',           'label' => 'Wi-Fi'],
                    ['icon' => 'fas fa-utensils',       'label' => 'Restaurant'],
                    ['icon' => 'fas fa-car',            'label' => 'Parking sécurisé'],
                ],
                'category_ids'      => [
                    $k['plages-lagunes'],
                    $k['parcs-reserves-naturelles'],
                    $k['sports-aventure'],
                ],
                'room_types'        => [
                    [
                        'name'         => 'Chambre Standard',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 26,
                        'price_xof'    => 55000,
                        'price_eur'    => 84,
                        'amenities'    => ['Climatisation', 'TV', 'Wifi'],
                        'thumbnail'    => null,
                    ],
                    [
                        'name'         => 'Chambre Vue Océan',
                        'max_adults'   => 2,
                        'max_children' => 1,
                        'area_m2'      => 32,
                        'price_xof'    => 80000,
                        'price_eur'    => 122,
                        'amenities'    => ['Vue océan', 'Balcon', 'Minibar', 'Baignoire'],
                        'thumbnail'    => null,
                    ],
                ],
                'booking_links'     => [
                    ['provider_name' => 'Booking.com', 'logo_url' => null, 'affiliate_url' => 'https://www.booking.com', 'is_official' => false, 'badge_text' => null, 'sort_order' => 1],
                    ['provider_name' => 'Expedia',     'logo_url' => null, 'affiliate_url' => 'https://www.expedia.fr',  'is_official' => false, 'badge_text' => null, 'sort_order' => 2],
                ],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 1,
            ],

        ];

        foreach ($accommodations as $data) {
            Accommodation::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }

        $this->command->info('✓ ' . count($accommodations) . ' hébergements seedés.');
    }
}
